import { DemoTransaction } from "../types";

export const demo2026Q1 = [
  // ❄️ January 2026
  {
    description: "Salary January",
    amount: 26000,
    type: "income",
    main_category: "Income",
    sub_category: "Wages",
    date: "2026-01-01",
  },
  {
    description: "Rent January",
    amount: 11500,
    type: "withdraw",
    main_category: "Fixed living expenses",
    sub_category: "Mortgage",
    date: "2026-01-03",
  },
  {
    description: "Groceries",
    amount: 2450,
    type: "withdraw",
    main_category: "Groceries",
    sub_category: "Grocery store",
    date: "2026-01-05",
  },
  {
    description: "Internet bill",
    amount: 720,
    type: "withdraw",
    main_category: "Fixed living expenses",
    sub_category: "Internet",
    date: "2026-01-06",
  },
  {
    description: "Coffee shop",
    amount: 420,
    type: "withdraw",
    main_category: "Cafe and restaurant",
    sub_category: "Cafe",
    date: "2026-01-07",
  },
  {
    description: "Fuel",
    amount: 1600,
    type: "withdraw",
    main_category: "Transportation and vehicles",
    sub_category: "Fuel and charging",
    date: "2026-01-09",
  },
  {
    description: "Streaming subscription",
    amount: 150,
    type: "withdraw",
    main_category: "Media and entertainment",
    sub_category: "Streaming services",
    date: "2026-01-10",
  },
  {
    description: "Pharmacy purchase",
    amount: 540,
    type: "withdraw",
    main_category: "Health and wellbeing",
    sub_category: "Pharmacy",
    date: "2026-01-12",
  },
  {
    description: "Children hobby supplies",
    amount: 1300,
    type: "withdraw",
    main_category: "Children",
    sub_category: "Other child expenses",
    date: "2026-01-15",
  },
  {
    description: "Interest from savings",
    amount: 360,
    type: "income",
    main_category: "Income",
    sub_category: "Dividends",
    date: "2026-01-28",
  },
  // ❄️ February 2026
  {
    description: "Salary February",
    amount: 26000,
    type: "income",
    main_category: "Income",
    sub_category: "Wages",
    date: "2026-02-01",
  },
  {
    description: "Rent February",
    amount: 11500,
    type: "withdraw",
    main_category: "Fixed living expenses",
    sub_category: "Mortgage",
    date: "2026-02-03",
  },
  {
    description: "Groceries",
    amount: 2350,
    type: "withdraw",
    main_category: "Groceries",
    sub_category: "Grocery store",
    date: "2026-02-05",
  },
  {
    description: "Electricity bill",
    amount: 640,
    type: "withdraw",
    main_category: "Fixed living expenses",
    sub_category: "Electricity",
    date: "2026-02-07",
  },
  {
    description: "Taxi ride",
    amount: 390,
    type: "withdraw",
    main_category: "Transportation and vehicles",
    sub_category: "Taxi",
    date: "2026-02-09",
  },
  {
    description: "Cinema tickets",
    amount: 480,
    type: "withdraw",
    main_category: "Media and entertainment",
    sub_category: "Movie Theater",
    date: "2026-02-11",
  },
  {
    description: "Gym membership",
    amount: 1200,
    type: "withdraw",
    main_category: "Health and wellbeing",
    sub_category: "Wellbeing",
    date: "2026-02-14",
  },
  {
    description: "Pet food",
    amount: 780,
    type: "withdraw",
    main_category: "Hobby and leisure",
    sub_category: "Pets",
    date: "2026-02-16",
  },
  {
    description: "Online course (UX)",
    amount: 1100,
    type: "withdraw",
    main_category: "Miscellaneous",
    sub_category: "Training and education",
    date: "2026-02-18",
  },
  {
    description: "Freelance project payment",
    amount: 6500,
    type: "income",
    main_category: "Income",
    sub_category: "Other income",
    date: "2026-02-22",
  },
  {
    description: "Interest from savings",
    amount: 370,
    type: "income",
    main_category: "Income",
    sub_category: "Dividends",
    date: "2026-02-27",
  },
  // 🌱 March 2026
  {
    description: "Salary March",
    amount: 26500,
    type: "income",
    main_category: "Income",
    sub_category: "Wages",
    date: "2026-03-01",
  },
  {
    description: "Rent March",
    amount: 11500,
    type: "withdraw",
    main_category: "Fixed living expenses",
    sub_category: "Mortgage",
    date: "2026-03-03",
  },
  {
    description: "Groceries",
    amount: 2550,
    type: "withdraw",
    main_category: "Groceries",
    sub_category: "Grocery store",
    date: "2026-03-05",
  },
  {
    description: "Public transport card",
    amount: 700,
    type: "withdraw",
    main_category: "Transportation and vehicles",
    sub_category: "Public transport",
    date: "2026-03-06",
  },
  {
    description: "Restaurant dinner",
    amount: 1250,
    type: "withdraw",
    main_category: "Cafe and restaurant",
    sub_category: "Restaurant",
    date: "2026-03-08",
  },
  {
    description: "Home improvement materials",
    amount: 2100,
    type: "withdraw",
    main_category: "Home and garden",
    sub_category: "Home improvement",
    date: "2026-03-10",
  },
  {
    description: "Beauty salon",
    amount: 1300,
    type: "withdraw",
    main_category: "Health and wellbeing",
    sub_category: "Beauty",
    date: "2026-03-12",
  },
  {
    description: "Children clothes",
    amount: 2200,
    type: "withdraw",
    main_category: "Children",
    sub_category: "Children's store",
    date: "2026-03-15",
  },
  {
    description: "Weekend cabin trip",
    amount: 4200,
    type: "withdraw",
    main_category: "Hobby and leisure",
    sub_category: "Cabin",
    date: "2026-03-18",
  },
  {
    description: "Travel train tickets",
    amount: 950,
    type: "withdraw",
    main_category: "Travel",
    sub_category: "Phone tickets",
    date: "2026-03-20",
  },
  {
    description: "Interest from savings",
    amount: 390,
    type: "income",
    main_category: "Income",
    sub_category: "Dividends",
    date: "2026-03-29",
  },
] as const satisfies readonly DemoTransaction[];
