import { DemoTransaction } from "../types";

export const demo2026Q2 = [
  // 🌸 April 2026
  {
    description: "Salary April",
    amount: 26500,
    type: "income",
    main_category: "Income",
    sub_category: "Wages",
    date: "2026-04-01",
  },
  {
    description: "Tax refund",
    amount: 4200,
    type: "income",
    main_category: "Income",
    sub_category: "Tax return",
    date: "2026-04-02",
  },
  {
    description: "Rent April",
    amount: 11500,
    type: "withdraw",
    main_category: "Fixed living expenses",
    sub_category: "Mortgage",
    date: "2026-04-03",
  },
  {
    description: "Groceries",
    amount: 2350,
    type: "withdraw",
    main_category: "Groceries",
    sub_category: "Supermarket",
    date: "2026-04-04",
  },
  {
    description: "Coffee",
    amount: 480,
    type: "withdraw",
    main_category: "Cafe and restaurant",
    sub_category: "Cafe",
    date: "2026-04-05",
  },
  {
    description: "Streaming subscription",
    amount: 180,
    type: "withdraw",
    main_category: "Media and entertainment",
    sub_category: "Streaming services",
    date: "2026-04-06",
  },
  {
    description: "Fuel",
    amount: 1650,
    type: "withdraw",
    main_category: "Transportation and vehicles",
    sub_category: "Fuel and charging",
    date: "2026-04-08",
  },
  {
    description: "Spring shopping",
    amount: 3100,
    type: "withdraw",
    main_category: "Clothing and gear",
    sub_category: "Clothing",
    date: "2026-04-10",
  },
  {
    description: "Electricity",
    amount: 600,
    type: "withdraw",
    main_category: "Fixed living expenses",
    sub_category: "Electricity",
    date: "2026-04-11",
  },
  {
    description: "Dinner out",
    amount: 1200,
    type: "withdraw",
    main_category: "Cafe and restaurant",
    sub_category: "Restaurant",
    date: "2026-04-13",
  },
  {
    description: "Freelance project",
    amount: 7000,
    type: "income",
    main_category: "Income",
    sub_category: "Other income",
    date: "2026-04-18",
  },
  {
    description: "Home decor",
    amount: 1500,
    type: "withdraw",
    main_category: "Home and garden",
    sub_category: "Interior",
    date: "2026-04-20",
  },

  // 🌼 May 2026
  {
    description: "Salary May",
    amount: 27000,
    type: "income",
    main_category: "Income",
    sub_category: "Wages",
    date: "2026-05-01",
  },
  {
    description: "Rent May",
    amount: 11500,
    type: "withdraw",
    main_category: "Fixed living expenses",
    sub_category: "Mortgage",
    date: "2026-05-03",
  },
  {
    description: "Groceries",
    amount: 2550,
    type: "withdraw",
    main_category: "Groceries",
    sub_category: "Supermarket",
    date: "2026-05-04",
  },
  {
    description: "Gym membership",
    amount: 1200,
    type: "withdraw",
    main_category: "Health and wellbeing",
    sub_category: "Wellbeing",
    date: "2026-05-05",
  },
  {
    description: "Taxi",
    amount: 420,
    type: "withdraw",
    main_category: "Transportation and vehicles",
    sub_category: "Taxi",
    date: "2026-05-06",
  },
  {
    description: "Weekend trip",
    amount: 4800,
    type: "withdraw",
    main_category: "Travel",
    sub_category: "Hotels",
    date: "2026-05-08",
  },
  {
    description: "Coffee",
    amount: 350,
    type: "withdraw",
    main_category: "Cafe and restaurant",
    sub_category: "Cafe",
    date: "2026-05-09",
  },
  {
    description: "Internet",
    amount: 730,
    type: "withdraw",
    main_category: "Fixed living expenses",
    sub_category: "Internet",
    date: "2026-05-10",
  },
  {
    description: "Gift purchase",
    amount: 1500,
    type: "withdraw",
    main_category: "Miscellaneous",
    sub_category: "Gifts",
    date: "2026-05-12",
  },
  {
    description: "Restaurant",
    amount: 900,
    type: "withdraw",
    main_category: "Cafe and restaurant",
    sub_category: "Restaurant",
    date: "2026-05-14",
  },
  {
    description: "Freelance work",
    amount: 6500,
    type: "income",
    main_category: "Income",
    sub_category: "Other income",
    date: "2026-05-18",
  },
  {
    description: "Car service",
    amount: 2200,
    type: "withdraw",
    main_category: "Transportation and vehicles",
    sub_category: "Maintenance",
    date: "2026-05-20",
  },
  {
    description: "Pet supplies",
    amount: 900,
    type: "withdraw",
    main_category: "Hobby and leisure",
    sub_category: "Pets",
    date: "2026-05-22",
  },
  {
    description: "Savings interest",
    amount: 400,
    type: "income",
    main_category: "Income",
    sub_category: "Dividends",
    date: "2026-05-28",
  },

  // ☀️ June 2026
  {
    description: "Salary June",
    amount: 27000,
    type: "income",
    main_category: "Income",
    sub_category: "Wages",
    date: "2026-06-01",
  },
  {
    description: "Rent June",
    amount: 11500,
    type: "withdraw",
    main_category: "Fixed living expenses",
    sub_category: "Mortgage",
    date: "2026-06-03",
  },
  {
    description: "Groceries",
    amount: 2600,
    type: "withdraw",
    main_category: "Groceries",
    sub_category: "Supermarket",
    date: "2026-06-04",
  },
  {
    description: "Flight tickets",
    amount: 7500,
    type: "withdraw",
    main_category: "Travel",
    sub_category: "Flights",
    date: "2026-06-06",
  },
  {
    description: "Fast food",
    amount: 500,
    type: "withdraw",
    main_category: "Cafe and restaurant",
    sub_category: "Fast food",
    date: "2026-06-07",
  },
  {
    description: "Phone service",
    amount: 750,
    type: "withdraw",
    main_category: "Fixed living expenses",
    sub_category: "Phone service",
    date: "2026-06-08",
  },
  {
    description: "Summer shopping",
    amount: 2100,
    type: "withdraw",
    main_category: "Clothing and gear",
    sub_category: "Clothing",
    date: "2026-06-10",
  },
  {
    description: "Cinema",
    amount: 500,
    type: "withdraw",
    main_category: "Media and entertainment",
    sub_category: "Movie Theater",
    date: "2026-06-12",
  },
  {
    description: "Doctor visit",
    amount: 800,
    type: "withdraw",
    main_category: "Health and wellbeing",
    sub_category: "Doctor",
    date: "2026-06-14",
  },
  {
    description: "Freelance project",
    amount: 8000,
    type: "income",
    main_category: "Income",
    sub_category: "Other income",
    date: "2026-06-18",
  },
  {
    description: "Garden furniture",
    amount: 3200,
    type: "withdraw",
    main_category: "Home and garden",
    sub_category: "Garden",
    date: "2026-06-20",
  },
  {
    description: "Dinner out",
    amount: 1500,
    type: "withdraw",
    main_category: "Cafe and restaurant",
    sub_category: "Restaurant",
    date: "2026-06-22",
  },
  {
    description: "Taxi airport",
    amount: 520,
    type: "withdraw",
    main_category: "Transportation and vehicles",
    sub_category: "Taxi",
    date: "2026-06-25",
  },
  {
    description: "Savings interest",
    amount: 420,
    type: "income",
    main_category: "Income",
    sub_category: "Dividends",
    date: "2026-06-29",
  },
] as const satisfies readonly DemoTransaction[];
