import { DemoTransaction } from "../types";

export const demo2026Q3 = [
  // ☀️ July 2026
  {
    description: "Salary July",
    amount: 27500,
    type: "income",
    main_category: "Income",
    sub_category: "Salary",
    date: "2026-07-01",
  },
  {
    description: "Mortgage July",
    amount: 11500,
    type: "withdraw",
    main_category: "Fixed living expenses",
    sub_category: "Mortgage",
    date: "2026-07-03",
  },
  {
    description: "Municipal fees",
    amount: 910,
    type: "withdraw",
    main_category: "Fixed living expenses",
    sub_category: "Municipal fees",
    date: "2026-07-04",
  },
  {
    description: "Grocery shopping",
    amount: 2460,
    type: "withdraw",
    main_category: "Groceries",
    sub_category: "Grocery store",
    date: "2026-07-05",
  },
  {
    description: "Internet bill",
    amount: 740,
    type: "withdraw",
    main_category: "Fixed living expenses",
    sub_category: "Internet",
    date: "2026-07-06",
  },
  {
    description: "Coffee with colleague",
    amount: 390,
    type: "withdraw",
    main_category: "Cafe and restaurant",
    sub_category: "Cafe",
    date: "2026-07-06",
  },
  {
    description: "Fuel top-up",
    amount: 1710,
    type: "withdraw",
    main_category: "Transportation and vehicles",
    sub_category: "Fuel and charging",
    date: "2026-07-08",
  },
  {
    description: "Parking downtown",
    amount: 180,
    type: "withdraw",
    main_category: "Transportation and vehicles",
    sub_category: "Parking",
    date: "2026-07-08",
  },
  {
    description: "Streaming bundle",
    amount: 199,
    type: "withdraw",
    main_category: "Media and entertainment",
    sub_category: "Streaming services",
    date: "2026-07-09",
  },
  {
    description: "Online bookstore order",
    amount: 540,
    type: "withdraw",
    main_category: "Media and entertainment",
    sub_category: "Bookseller",
    date: "2026-07-10",
  },
  {
    description: "Pharmacy purchase",
    amount: 610,
    type: "withdraw",
    main_category: "Health and wellbeing",
    sub_category: "Pharmacy",
    date: "2026-07-11",
  },
  {
    description: "Sporting goods",
    amount: 1850,
    type: "withdraw",
    main_category: "Clothing and gear",
    sub_category: "Sporting goods",
    date: "2026-07-12",
  },
  {
    description: "Children's store visit",
    amount: 1450,
    type: "withdraw",
    main_category: "Children",
    sub_category: "Children's store",
    date: "2026-07-14",
  },
  {
    description: "Movie night tickets",
    amount: 420,
    type: "withdraw",
    main_category: "Hobby and leisure",
    sub_category: "Movie Theater",
    date: "2026-07-15",
  },
  {
    description: "Garden flowers and soil",
    amount: 980,
    type: "withdraw",
    main_category: "Home and garden",
    sub_category: "Garden and flowers",
    date: "2026-07-16",
  },
  {
    description: "Freelance design payment",
    amount: 5200,
    type: "income",
    main_category: "Income",
    sub_category: "Other income",
    date: "2026-07-21",
  },
  {
    description: "Taxi ride after concert",
    amount: 360,
    type: "withdraw",
    main_category: "Transportation and vehicles",
    sub_category: "Taxi",
    date: "2026-07-22",
  },
  {
    description: "Pet food and toys",
    amount: 830,
    type: "withdraw",
    main_category: "Hobby and leisure",
    sub_category: "Pets",
    date: "2026-07-23",
  },
  {
    description: "Weekend train e-tickets",
    amount: 760,
    type: "withdraw",
    main_category: "Travel",
    sub_category: "Phone tickets",
    date: "2026-07-24",
  },
  {
    description: "Dividends July",
    amount: 410,
    type: "income",
    main_category: "Income",
    sub_category: "Dividends",
    date: "2026-07-29",
  },

  // 🌻 August 2026
  {
    description: "Salary August",
    amount: 27500,
    type: "income",
    main_category: "Income",
    sub_category: "Salary",
    date: "2026-08-01",
  },
  {
    description: "Mortgage August",
    amount: 11500,
    type: "withdraw",
    main_category: "Fixed living expenses",
    sub_category: "Mortgage",
    date: "2026-08-03",
  },
  {
    description: "Grocery shopping",
    amount: 2520,
    type: "withdraw",
    main_category: "Groceries",
    sub_category: "Grocery store",
    date: "2026-08-04",
  },
  {
    description: "Cleaning and household supplies",
    amount: 690,
    type: "withdraw",
    main_category: "Groceries",
    sub_category: "Other household items",
    date: "2026-08-04",
  },
  {
    description: "Electricity bill",
    amount: 620,
    type: "withdraw",
    main_category: "Fixed living expenses",
    sub_category: "Electricity",
    date: "2026-08-05",
  },
  {
    description: "Convenience store snacks",
    amount: 240,
    type: "withdraw",
    main_category: "Cafe and restaurant",
    sub_category: "Convenience store",
    date: "2026-08-06",
  },
  {
    description: "Public transport card",
    amount: 720,
    type: "withdraw",
    main_category: "Transportation and vehicles",
    sub_category: "Public transport",
    date: "2026-08-07",
  },
  {
    description: "Car maintenance parts",
    amount: 2860,
    type: "withdraw",
    main_category: "Transportation and vehicles",
    sub_category: "Car parts and maintenance",
    date: "2026-08-09",
  },
  {
    description: "Magazine subscription",
    amount: 210,
    type: "withdraw",
    main_category: "Media and entertainment",
    sub_category: "Magazines",
    date: "2026-08-10",
  },
  {
    description: "Wellbeing membership",
    amount: 1200,
    type: "withdraw",
    main_category: "Health and wellbeing",
    sub_category: "Wellbeing",
    date: "2026-08-11",
  },
  {
    description: "Medical checkup",
    amount: 950,
    type: "withdraw",
    main_category: "Health and wellbeing",
    sub_category: "Medical services",
    date: "2026-08-13",
  },
  {
    description: "Interior decor purchase",
    amount: 2650,
    type: "withdraw",
    main_category: "Home and garden",
    sub_category: "Furniture and interior",
    date: "2026-08-14",
  },
  {
    description: "Weekend hotel stay",
    amount: 5400,
    type: "withdraw",
    main_category: "Travel",
    sub_category: "Accommodation",
    date: "2026-08-16",
  },
  {
    description: "Local travel expenses",
    amount: 880,
    type: "withdraw",
    main_category: "Travel",
    sub_category: "Other travel",
    date: "2026-08-16",
  },
  {
    description: "Marketplace order",
    amount: 730,
    type: "withdraw",
    main_category: "Hobby and leisure",
    sub_category: "Online marketplace",
    date: "2026-08-18",
  },
  {
    description: "Gift for friends",
    amount: 980,
    type: "withdraw",
    main_category: "Miscellaneous",
    sub_category: "Gift",
    date: "2026-08-20",
  },
  {
    description: "Children hobby expenses",
    amount: 1180,
    type: "withdraw",
    main_category: "Children",
    sub_category: "Other child expenses",
    date: "2026-08-21",
  },
  {
    description: "Summer side project",
    amount: 4800,
    type: "income",
    main_category: "Income",
    sub_category: "Other income",
    date: "2026-08-23",
  },
  {
    description: "City museum visit",
    amount: 320,
    type: "withdraw",
    main_category: "Hobby and leisure",
    sub_category: "Museum",
    date: "2026-08-24",
  },
  {
    description: "Dividends August",
    amount: 430,
    type: "income",
    main_category: "Income",
    sub_category: "Dividends",
    date: "2026-08-28",
  },
  {
    description: "Phone service",
    amount: 760,
    type: "withdraw",
    main_category: "Fixed living expenses",
    sub_category: "Phone service",
    date: "2026-08-29",
  },

  // 🍂 September 2026
  {
    description: "Salary September",
    amount: 28000,
    type: "income",
    main_category: "Income",
    sub_category: "Salary",
    date: "2026-09-01",
  },
  {
    description: "Mortgage September",
    amount: 11500,
    type: "withdraw",
    main_category: "Fixed living expenses",
    sub_category: "Mortgage",
    date: "2026-09-03",
  },
  {
    description: "Home insurance",
    amount: 1450,
    type: "withdraw",
    main_category: "Fixed living expenses",
    sub_category: "Home insurance",
    date: "2026-09-04",
  },
  {
    description: "Grocery shopping",
    amount: 2590,
    type: "withdraw",
    main_category: "Groceries",
    sub_category: "Grocery store",
    date: "2026-09-05",
  },
  {
    description: "Cafeteria lunch",
    amount: 340,
    type: "withdraw",
    main_category: "Cafe and restaurant",
    sub_category: "Cafeteria",
    date: "2026-09-06",
  },
  {
    description: "Candy shop",
    amount: 190,
    type: "withdraw",
    main_category: "Cafe and restaurant",
    sub_category: "Candy",
    date: "2026-09-07",
  },
  {
    description: "Fuel for car",
    amount: 1640,
    type: "withdraw",
    main_category: "Transportation and vehicles",
    sub_category: "Fuel and charging",
    date: "2026-09-08",
  },
  {
    description: "Vehicle fees",
    amount: 980,
    type: "withdraw",
    main_category: "Transportation and vehicles",
    sub_category: "Vehicle fees",
    date: "2026-09-10",
  },
  {
    description: "Streaming subscription",
    amount: 199,
    type: "withdraw",
    main_category: "Media and entertainment",
    sub_category: "Streaming services",
    date: "2026-09-11",
  },
  {
    description: "Design course payment",
    amount: 1350,
    type: "withdraw",
    main_category: "Miscellaneous",
    sub_category: "Training and education",
    date: "2026-09-12",
  },
  {
    description: "Dentist visit",
    amount: 1750,
    type: "withdraw",
    main_category: "Health and wellbeing",
    sub_category: "Dentist",
    date: "2026-09-14",
  },
  {
    description: "Craft supplies",
    amount: 690,
    type: "withdraw",
    main_category: "Hobby and leisure",
    sub_category: "Crafts",
    date: "2026-09-15",
  },
  {
    description: "Home improvement materials",
    amount: 2140,
    type: "withdraw",
    main_category: "Home and garden",
    sub_category: "Home improvement",
    date: "2026-09-17",
  },
  {
    description: "New autumn shoes",
    amount: 2290,
    type: "withdraw",
    main_category: "Clothing and gear",
    sub_category: "Shoes",
    date: "2026-09-18",
  },
  {
    description: "School supplies for child",
    amount: 960,
    type: "withdraw",
    main_category: "Children",
    sub_category: "Other child expenses",
    date: "2026-09-19",
  },
  {
    description: "Weekend cabin booking",
    amount: 3600,
    type: "withdraw",
    main_category: "Hobby and leisure",
    sub_category: "Cabin",
    date: "2026-09-20",
  },
  {
    description: "Side shift wages",
    amount: 3200,
    type: "income",
    main_category: "Income",
    sub_category: "Wages",
    date: "2026-09-22",
  },
  {
    description: "Cash withdrawal",
    amount: 2500,
    type: "withdraw",
    main_category: "Miscellaneous",
    sub_category: "Cash machine",
    date: "2026-09-24",
  },
  {
    description: "Newspaper subscription",
    amount: 180,
    type: "withdraw",
    main_category: "Media and entertainment",
    sub_category: "Newspaper",
    date: "2026-09-25",
  },
  {
    description: "Dividends September",
    amount: 440,
    type: "income",
    main_category: "Income",
    sub_category: "Dividends",
    date: "2026-09-29",
  },
] as const satisfies readonly DemoTransaction[];
