import { DemoTransaction } from "../types";

export const demo2026Q4 = [
  // 🎃 October 2026
  {
    description: "Salary October",
    amount: 28000,
    type: "income",
    main_category: "Income",
    sub_category: "Salary",
    date: "2026-10-01",
  },
  {
    description: "Mortgage October",
    amount: 11500,
    type: "withdraw",
    main_category: "Fixed living expenses",
    sub_category: "Mortgage",
    date: "2026-10-03",
  },
  {
    description: "Electricity bill",
    amount: 670,
    type: "withdraw",
    main_category: "Fixed living expenses",
    sub_category: "Electricity",
    date: "2026-10-04",
  },
  {
    description: "Grocery shopping",
    amount: 2480,
    type: "withdraw",
    main_category: "Groceries",
    sub_category: "Grocery store",
    date: "2026-10-05",
  },
  {
    description: "Cafe breakfast",
    amount: 310,
    type: "withdraw",
    main_category: "Cafe and restaurant",
    sub_category: "Cafe",
    date: "2026-10-06",
  },
  {
    description: "Public transport card",
    amount: 720,
    type: "withdraw",
    main_category: "Transportation and vehicles",
    sub_category: "Public transport",
    date: "2026-10-07",
  },
  {
    description: "TV package",
    amount: 260,
    type: "withdraw",
    main_category: "Media and entertainment",
    sub_category: "TV",
    date: "2026-10-08",
  },
  {
    description: "Dental cleaning",
    amount: 890,
    type: "withdraw",
    main_category: "Health and wellbeing",
    sub_category: "Dentist",
    date: "2026-10-09",
  },
  {
    description: "Clothing order",
    amount: 1840,
    type: "withdraw",
    main_category: "Clothing and gear",
    sub_category: "Clothing",
    date: "2026-10-11",
  },
  {
    description: "Toy store purchase",
    amount: 740,
    type: "withdraw",
    main_category: "Hobby and leisure",
    sub_category: "Toys",
    date: "2026-10-12",
  },
  {
    description: "Peer-to-peer payment",
    amount: 600,
    type: "withdraw",
    main_category: "Miscellaneous",
    sub_category: "Peer-to-peer payment",
    date: "2026-10-13",
  },
  {
    description: "Weekend car rental",
    amount: 1650,
    type: "withdraw",
    main_category: "Transportation and vehicles",
    sub_category: "Car rental",
    date: "2026-10-15",
  },
  {
    description: "Autumn trip deposit",
    amount: 2900,
    type: "withdraw",
    main_category: "Travel",
    sub_category: "Travel agency",
    date: "2026-10-16",
  },
  {
    description: "Cinema evening",
    amount: 460,
    type: "withdraw",
    main_category: "Hobby and leisure",
    sub_category: "Movie Theater",
    date: "2026-10-18",
  },
  {
    description: "Plumbing repair",
    amount: 2100,
    type: "withdraw",
    main_category: "Home and garden",
    sub_category: "Tradesperson",
    date: "2026-10-19",
  },
  {
    description: "Night out with friends",
    amount: 1320,
    type: "withdraw",
    main_category: "Cafe and restaurant",
    sub_category: "Bars and nightlife",
    date: "2026-10-21",
  },
  {
    description: "Printed photo order",
    amount: 540,
    type: "withdraw",
    main_category: "Hobby and leisure",
    sub_category: "Photography",
    date: "2026-10-23",
  },
  {
    description: "Bonus payment",
    amount: 5600,
    type: "income",
    main_category: "Income",
    sub_category: "Other income",
    date: "2026-10-25",
  },
  {
    description: "Dividends October",
    amount: 420,
    type: "income",
    main_category: "Income",
    sub_category: "Dividends",
    date: "2026-10-29",
  },
  {
    description: "Alarm service",
    amount: 290,
    type: "withdraw",
    main_category: "Fixed living expenses",
    sub_category: "Alarm",
    date: "2026-10-30",
  },
  // 🌫️ November 2026
  {
    description: "Salary November",
    amount: 28200,
    type: "income",
    main_category: "Income",
    sub_category: "Salary",
    date: "2026-11-01",
  },
  {
    description: "Mortgage November",
    amount: 11500,
    type: "withdraw",
    main_category: "Fixed living expenses",
    sub_category: "Mortgage",
    date: "2026-11-03",
  },
  {
    description: "Internet bill",
    amount: 750,
    type: "withdraw",
    main_category: "Fixed living expenses",
    sub_category: "Internet",
    date: "2026-11-04",
  },
  {
    description: "Property management fee",
    amount: 430,
    type: "withdraw",
    main_category: "Fixed living expenses",
    sub_category: "Property management",
    date: "2026-11-05",
  },
  {
    description: "Grocery shopping",
    amount: 2660,
    type: "withdraw",
    main_category: "Groceries",
    sub_category: "Grocery store",
    date: "2026-11-06",
  },
  {
    description: "Restaurant dinner",
    amount: 1180,
    type: "withdraw",
    main_category: "Cafe and restaurant",
    sub_category: "Restaurant",
    date: "2026-11-07",
  },
  {
    description: "Gaming app purchase",
    amount: 260,
    type: "withdraw",
    main_category: "Media and entertainment",
    sub_category: "Apps and gaming",
    date: "2026-11-08",
  },
  {
    description: "TV package",
    amount: 260,
    type: "withdraw",
    main_category: "Media and entertainment",
    sub_category: "TV",
    date: "2026-11-09",
  },
  {
    description: "Beauty salon visit",
    amount: 1350,
    type: "withdraw",
    main_category: "Health and wellbeing",
    sub_category: "Beauty",
    date: "2026-11-10",
  },
  {
    description: "Health goods",
    amount: 520,
    type: "withdraw",
    main_category: "Health and wellbeing",
    sub_category: "Health goods",
    date: "2026-11-11",
  },
  {
    description: "Kitchen appliance purchase",
    amount: 4790,
    type: "withdraw",
    main_category: "Home and garden",
    sub_category: "Appliances",
    date: "2026-11-13",
  },
  {
    description: "Toll road payment",
    amount: 140,
    type: "withdraw",
    main_category: "Transportation and vehicles",
    sub_category: "Toll",
    date: "2026-11-14",
  },
  {
    description: "Charity donation",
    amount: 500,
    type: "withdraw",
    main_category: "Miscellaneous",
    sub_category: "Membership and charity",
    date: "2026-11-15",
  },
  {
    description: "Student loan payment",
    amount: 2100,
    type: "withdraw",
    main_category: "Other loan and debt",
    sub_category: "Student loan",
    date: "2026-11-16",
  },
  {
    description: "Children's jacket",
    amount: 1680,
    type: "withdraw",
    main_category: "Children",
    sub_category: "Children's store",
    date: "2026-11-18",
  },
  {
    description: "Exercise class package",
    amount: 890,
    type: "withdraw",
    main_category: "Hobby and leisure",
    sub_category: "Exercise",
    date: "2026-11-19",
  },
  {
    description: "Household supplies",
    amount: 620,
    type: "withdraw",
    main_category: "Groceries",
    sub_category: "Other household items",
    date: "2026-11-20",
  },
  {
    description: "Mechanic inspection",
    amount: 1250,
    type: "withdraw",
    main_category: "Transportation and vehicles",
    sub_category: "Mechanic",
    date: "2026-11-22",
  },
  {
    description: "Newspaper subscription",
    amount: 180,
    type: "withdraw",
    main_category: "Media and entertainment",
    sub_category: "Newspaper",
    date: "2026-11-23",
  },
  {
    description: "Freelance consulting",
    amount: 6100,
    type: "income",
    main_category: "Income",
    sub_category: "Other income",
    date: "2026-11-25",
  },
  {
    description: "Dividends November",
    amount: 450,
    type: "income",
    main_category: "Income",
    sub_category: "Dividends",
    date: "2026-11-29",
  },
  {
    description: "Bank fees",
    amount: 95,
    type: "withdraw",
    main_category: "Miscellaneous",
    sub_category: "Interest and fees",
    date: "2026-11-30",
  },
  // 🎄 December 2026
  {
    description: "Salary December",
    amount: 28500,
    type: "income",
    main_category: "Income",
    sub_category: "Salary",
    date: "2026-12-01",
  },
  {
    description: "Year-end bonus",
    amount: 9000,
    type: "income",
    main_category: "Income",
    sub_category: "Other income",
    date: "2026-12-02",
  },
  {
    description: "Mortgage December",
    amount: 11500,
    type: "withdraw",
    main_category: "Fixed living expenses",
    sub_category: "Mortgage",
    date: "2026-12-03",
  },
  {
    description: "Municipal fees",
    amount: 980,
    type: "withdraw",
    main_category: "Fixed living expenses",
    sub_category: "Municipal fees",
    date: "2026-12-04",
  },
  {
    description: "Holiday grocery shopping",
    amount: 3120,
    type: "withdraw",
    main_category: "Groceries",
    sub_category: "Grocery store",
    date: "2026-12-05",
  },
  {
    description: "Holiday treats",
    amount: 420,
    type: "withdraw",
    main_category: "Cafe and restaurant",
    sub_category: "Candy",
    date: "2026-12-06",
  },
  {
    description: "Dinner out",
    amount: 1650,
    type: "withdraw",
    main_category: "Cafe and restaurant",
    sub_category: "Restaurant",
    date: "2026-12-07",
  },
  {
    description: "Gift shopping",
    amount: 3400,
    type: "withdraw",
    main_category: "Miscellaneous",
    sub_category: "Gift",
    date: "2026-12-08",
  },
  {
    description: "Gift cards for family",
    amount: 1200,
    type: "withdraw",
    main_category: "Hobby and leisure",
    sub_category: "Gift card",
    date: "2026-12-09",
  },
  {
    description: "Holiday cabin accommodation",
    amount: 6200,
    type: "withdraw",
    main_category: "Travel",
    sub_category: "Accommodation",
    date: "2026-12-10",
  },
  {
    description: "Holiday travel expenses",
    amount: 1100,
    type: "withdraw",
    main_category: "Travel",
    sub_category: "Other travel",
    date: "2026-12-10",
  },
  {
    description: "Winter coat",
    amount: 2890,
    type: "withdraw",
    main_category: "Clothing and gear",
    sub_category: "Clothing",
    date: "2026-12-12",
  },
  {
    description: "Jewelry gift",
    amount: 1750,
    type: "withdraw",
    main_category: "Clothing and gear",
    sub_category: "Jewelry and accessories",
    date: "2026-12-13",
  },
  {
    description: "Pet holiday supplies",
    amount: 940,
    type: "withdraw",
    main_category: "Hobby and leisure",
    sub_category: "Pets",
    date: "2026-12-14",
  },
  {
    description: "Heating repair",
    amount: 3700,
    type: "withdraw",
    main_category: "Home and garden",
    sub_category: "Tradesperson",
    date: "2026-12-15",
  },
  {
    description: "Cash withdrawal",
    amount: 3000,
    type: "withdraw",
    main_category: "Miscellaneous",
    sub_category: "Cash machine",
    date: "2026-12-16",
  },
  {
    description: "Taxes payment",
    amount: 1600,
    type: "withdraw",
    main_category: "Miscellaneous",
    sub_category: "Taxes",
    date: "2026-12-17",
  },
  {
    description: "Night out",
    amount: 1480,
    type: "withdraw",
    main_category: "Cafe and restaurant",
    sub_category: "Bars and nightlife",
    date: "2026-12-19",
  },
  {
    description: "Phone service",
    amount: 780,
    type: "withdraw",
    main_category: "Fixed living expenses",
    sub_category: "Phone service",
    date: "2026-12-20",
  },
  {
    description: "Streaming subscription",
    amount: 199,
    type: "withdraw",
    main_category: "Media and entertainment",
    sub_category: "Streaming services",
    date: "2026-12-21",
  },
  {
    description: "Annual web services renewal",
    amount: 690,
    type: "withdraw",
    main_category: "Hobby and leisure",
    sub_category: "Web services",
    date: "2026-12-22",
  },
  {
    description: "Fuel top-up",
    amount: 1540,
    type: "withdraw",
    main_category: "Transportation and vehicles",
    sub_category: "Fuel and charging",
    date: "2026-12-23",
  },
  {
    description: "Parking city center",
    amount: 220,
    type: "withdraw",
    main_category: "Transportation and vehicles",
    sub_category: "Parking",
    date: "2026-12-23",
  },
  {
    description: "Home insurance",
    amount: 1460,
    type: "withdraw",
    main_category: "Fixed living expenses",
    sub_category: "Home insurance",
    date: "2026-12-24",
  },
  {
    description: "Children's holiday gifts",
    amount: 1580,
    type: "withdraw",
    main_category: "Children",
    sub_category: "Children's store",
    date: "2026-12-26",
  },
  {
    description: "Holiday shift wages",
    amount: 2600,
    type: "income",
    main_category: "Income",
    sub_category: "Wages",
    date: "2026-12-27",
  },
  {
    description: "Dividends December",
    amount: 470,
    type: "income",
    main_category: "Income",
    sub_category: "Dividends",
    date: "2026-12-29",
  },
  {
    description: "Transfer to family",
    amount: 850,
    type: "withdraw",
    main_category: "Miscellaneous",
    sub_category: "Transfer",
    date: "2026-12-30",
  },
] as const satisfies readonly DemoTransaction[];
