import { DemoTransaction } from "../types";

export const demo2025Q2 = [
  // 🌸 April
  {
    description: "Salary April",
    amount: 24000,
    type: "income",
    main_category: "Income",
    sub_category: "Wages",
    date: "2025-04-01",
  },
  {
    description: "Rent April",
    amount: 11000,
    type: "withdraw",
    main_category: "Fixed living expenses",
    sub_category: "Mortgage",
    date: "2025-04-03",
  },
  {
    description: "Groceries",
    amount: 2100,
    type: "withdraw",
    main_category: "Groceries",
    sub_category: "Supermarket",
    date: "2025-04-05",
  },
  {
    description: "Coffee and snacks",
    amount: 450,
    type: "withdraw",
    main_category: "Cafe and restaurant",
    sub_category: "Cafe",
    date: "2025-04-05",
  },
  {
    description: "Groceries",
    amount: 2200,
    type: "withdraw",
    main_category: "Groceries",
    sub_category: "Supermarket",
    date: "2025-04-06",
  },
  {
    description: "Pharmacy purchase",
    amount: 520,
    type: "withdraw",
    main_category: "Health and wellbeing",
    sub_category: "Pharmacy",
    date: "2025-04-07",
  },
  {
    description: "Convenience store snacks",
    amount: 320,
    type: "withdraw",
    main_category: "Cafe and restaurant",
    sub_category: "Convenience store",
    date: "2025-04-08",
  },
  {
    description: "Electricity bill",
    amount: 580,
    type: "withdraw",
    main_category: "Fixed living expenses",
    sub_category: "Electricity",
    date: "2025-04-10",
  },
  {
    description: "Movie night tickets",
    amount: 300,
    type: "withdraw",
    main_category: "Media and entertainment",
    sub_category: "Movie Theater",
    date: "2025-04-12",
  },
  {
    description: "Pharmacy",
    amount: 430,
    type: "withdraw",
    main_category: "Health and wellbeing",
    sub_category: "Pharmacy",
    date: "2025-04-12",
  },
  {
    description: "Taxi ride home",
    amount: 370,
    type: "withdraw",
    main_category: "Transportation and vehicles",
    sub_category: "Taxi",
    date: "2025-04-12",
  },
  {
    description: "Children's toys",
    amount: 1200,
    type: "withdraw",
    main_category: "Hobby and leisure",
    sub_category: "Toys",
    date: "2025-04-15",
  },
  {
    description: "Home insurance payment",
    amount: 1500,
    type: "withdraw",
    main_category: "Fixed living expenses",
    sub_category: "Home insurance",
    date: "2025-04-15",
  },
  {
    description: "Jewelry purchase",
    amount: 3400,
    type: "withdraw",
    main_category: "Clothing and gear",
    sub_category: "Jewelry and accessories",
    date: "2025-04-20",
  },
  {
    description: "Pet supplies",
    amount: 850,
    type: "withdraw",
    main_category: "Hobby and leisure",
    sub_category: "Pets",
    date: "2025-04-22",
  },

  // 🌼 May
  {
    description: "Salary May",
    amount: 25000,
    type: "income",
    main_category: "Income",
    sub_category: "Wages",
    date: "2025-05-01",
  },
  {
    description: "Rent May",
    amount: 11000,
    type: "withdraw",
    main_category: "Fixed living expenses",
    sub_category: "Mortgage",
    date: "2025-05-03",
  },
  {
    description: "Sporting goods store",
    amount: 1800,
    type: "withdraw",
    main_category: "Clothing and gear",
    sub_category: "Sporting goods",
    date: "2025-05-05",
  },
  {
    description: "Groceries",
    amount: 2400,
    type: "withdraw",
    main_category: "Groceries",
    sub_category: "Supermarket",
    date: "2025-05-06",
  },
  {
    description: "Electricity",
    amount: 600,
    type: "withdraw",
    main_category: "Fixed living expenses",
    sub_category: "Electricity",
    date: "2025-05-10",
  },
  {
    description: "Credit card payment",
    amount: 5400,
    type: "withdraw",
    main_category: "Miscellaneous",
    sub_category: "Credit card payment",
    date: "2025-05-10",
  },
  {
    description: "Taxi fare",
    amount: 380,
    type: "withdraw",
    main_category: "Transportation and vehicles",
    sub_category: "Taxi",
    date: "2025-05-12",
  },
  {
    description: "Coffee shop",
    amount: 350,
    type: "withdraw",
    main_category: "Cafe and restaurant",
    sub_category: "Cafe",
    date: "2025-05-14",
  },
  {
    description: "Dental check-up",
    amount: 1600,
    type: "withdraw",
    main_category: "Health and wellbeing",
    sub_category: "Dentist",
    date: "2025-05-18",
  },

  // ☀️ June
  {
    description: "Salary June",
    amount: 25000,
    type: "income",
    main_category: "Income",
    sub_category: "Wages",
    date: "2025-06-01",
  },
  {
    description: "Rent June",
    amount: 11000,
    type: "withdraw",
    main_category: "Fixed living expenses",
    sub_category: "Mortgage",
    date: "2025-06-03",
  },
  {
    description: "Groceries",
    amount: 2300,
    type: "withdraw",
    main_category: "Groceries",
    sub_category: "Supermarket",
    date: "2025-06-05",
  },
  {
    description: "Gardening flowers",
    amount: 1300,
    type: "withdraw",
    main_category: "Home and garden",
    sub_category: "Garden and flowers",
    date: "2025-06-07",
  },
  {
    description: "Fast food lunch",
    amount: 450,
    type: "withdraw",
    main_category: "Cafe and restaurant",
    sub_category: "Fast food",
    date: "2025-06-10",
  },
  {
    description: "Phone service monthly",
    amount: 750,
    type: "withdraw",
    main_category: "Fixed living expenses",
    sub_category: "Phone service",
    date: "2025-06-11",
  },
  {
    description: "Pharmacy",
    amount: 350,
    type: "withdraw",
    main_category: "Health and wellbeing",
    sub_category: "Pharmacy",
    date: "2025-06-15",
  },
  {
    description: "Freelance project",
    amount: 5000,
    type: "income",
    main_category: "Income",
    sub_category: "Other income",
    date: "2025-06-20",
  },
  {
    description: "Mechanic service",
    amount: 2800,
    type: "withdraw",
    main_category: "Transportation and vehicles",
    sub_category: "Mechanic",
    date: "2025-06-23",
  },
] as const satisfies readonly DemoTransaction[];
