import { DemoTransaction } from "../types";

export const demo2025Q3 = [
  // 🌻 July
  {
    description: "Salary July",
    amount: 25000,
    type: "income",
    main_category: "Income",
    sub_category: "Wages",
    date: "2025-07-01",
  },
  {
    description: "Rent July",
    amount: 11000,
    type: "withdraw",
    main_category: "Fixed living expenses",
    sub_category: "Mortgage",
    date: "2025-07-01",
  },
  {
    description: "Groceries",
    amount: 2150,
    type: "withdraw",
    main_category: "Groceries",
    sub_category: "Supermarket",
    date: "2025-07-03",
  },
  {
    description: "Online gaming app purchase",
    amount: 300,
    type: "withdraw",
    main_category: "Media and entertainment",
    sub_category: "Apps and gaming",
    date: "2025-07-04",
  },
  {
    description: "Movie tickets",
    amount: 260,
    type: "withdraw",
    main_category: "Media and entertainment",
    sub_category: "Movie Theater",
    date: "2025-07-07",
  },
  {
    description: "Tool for home repair",
    amount: 950,
    type: "withdraw",
    main_category: "Home and garden",
    sub_category: "Tools",
    date: "2025-07-09",
  },
  {
    description: "Streaming service",
    amount: 120,
    type: "withdraw",
    main_category: "Media and entertainment",
    sub_category: "Streaming services",
    date: "2025-07-11",
  },
  {
    description: "Childcare supplies",
    amount: 1150,
    type: "withdraw",
    main_category: "Children",
    sub_category: "Other child expenses",
    date: "2025-07-17",
  },
  {
    description: "Car parts purchase",
    amount: 2400,
    type: "withdraw",
    main_category: "Transportation and vehicles",
    sub_category: "Car parts and maintenance",
    date: "2025-07-22",
  },
  // 🌾 August
  {
    description: "Salary August",
    amount: 25000,
    type: "income",
    main_category: "Income",
    sub_category: "Wages",
    date: "2025-08-01",
  },
  {
    description: "Rent August",
    amount: 11000,
    type: "withdraw",
    main_category: "Fixed living expenses",
    sub_category: "Mortgage",
    date: "2025-08-03",
  },
  {
    description: "Cash withdrawal",
    amount: 4000,
    type: "withdraw",
    main_category: "Miscellaneous",
    sub_category: "Cash machine",
    date: "2025-08-04",
  },
  {
    description: "Online course on UI design",
    amount: 1200,
    type: "withdraw",
    main_category: "Miscellaneous",
    sub_category: "Training and education",
    date: "2025-08-05",
  },
  {
    description: "Groceries",
    amount: 2250,
    type: "withdraw",
    main_category: "Groceries",
    sub_category: "Supermarket",
    date: "2025-08-06",
  },
  {
    description: "Beauty salon visit",
    amount: 950,
    type: "withdraw",
    main_category: "Health and wellbeing",
    sub_category: "Beauty",
    date: "2025-08-07",
  },
  {
    description: "Dinner out",
    amount: 900,
    type: "withdraw",
    main_category: "Cafe and restaurant",
    sub_category: "Restaurant",
    date: "2025-08-08",
  },
  {
    description: "Cabin rental weekend",
    amount: 3800,
    type: "withdraw",
    main_category: "Hobby and leisure",
    sub_category: "Cabin",
    date: "2025-08-08",
  },
  {
    description: "Public transport monthly card",
    amount: 650,
    type: "withdraw",
    main_category: "Transportation and vehicles",
    sub_category: "Public transport",
    date: "2025-08-09",
  },
  {
    description: "Gym membership",
    amount: 1200,
    type: "withdraw",
    main_category: "Health and wellbeing",
    sub_category: "Wellbeing",
    date: "2025-08-10",
  },
  {
    description: "Newspaper subscription",
    amount: 180,
    type: "withdraw",
    main_category: "Media and entertainment",
    sub_category: "Newspaper",
    date: "2025-08-11",
  },
  {
    description: "Fuel",
    amount: 1500,
    type: "withdraw",
    main_category: "Transportation and vehicles",
    sub_category: "Fuel and charging",
    date: "2025-08-12",
  },
  {
    description: "Magazine subscription",
    amount: 350,
    type: "withdraw",
    main_category: "Media and entertainment",
    sub_category: "Magazines",
    date: "2025-08-13",
  },
  {
    description: "Other child expenses",
    amount: 1100,
    type: "withdraw",
    main_category: "Children",
    sub_category: "Other child expenses",
    date: "2025-08-14",
  },
  {
    description: "Pet food",
    amount: 700,
    type: "withdraw",
    main_category: "Hobby and leisure",
    sub_category: "Pets",
    date: "2025-08-15",
  },
  {
    description: "Eye exam at optometrist",
    amount: 1300,
    type: "withdraw",
    main_category: "Health and wellbeing",
    sub_category: "Eye care",
    date: "2025-08-16",
  },
  {
    description: "Interest from savings",
    amount: 350,
    type: "income",
    main_category: "Income",
    sub_category: "Dividends",
    date: "2025-08-18",
  },
  {
    description: "Train ticket to nearby city",
    amount: 780,
    type: "withdraw",
    main_category: "Travel",
    sub_category: "Phone tickets",
    date: "2025-08-19",
  },
  {
    description: "Electricity bill",
    amount: 580,
    type: "withdraw",
    main_category: "Fixed living expenses",
    sub_category: "Electricity",
    date: "2025-08-20",
  },
  {
    description: "Charity donation",
    amount: 500,
    type: "withdraw",
    main_category: "Miscellaneous",
    sub_category: "Membership and charity",
    date: "2025-08-21",
  },
  {
    description: "Gambling site deposit",
    amount: 400,
    type: "withdraw",
    main_category: "Media and entertainment",
    sub_category: "Gambling",
    date: "2025-08-23",
  },
  {
    description: "Online course",
    amount: 950,
    type: "withdraw",
    main_category: "Miscellaneous",
    sub_category: "Training and education",
    date: "2025-08-25",
  },
  // September
  {
    description: "Salary September",
    amount: 25000,
    type: "income",
    main_category: "Income",
    sub_category: "Wages",
    date: "2025-09-01",
  },
  {
    description: "Rent September",
    amount: 11000,
    type: "withdraw",
    main_category: "Fixed living expenses",
    sub_category: "Mortgage",
    date: "2025-09-03",
  },
  {
    description: "Groceries",
    amount: 2300,
    type: "withdraw",
    main_category: "Groceries",
    sub_category: "Supermarket",
    date: "2025-09-05",
  },
  {
    description: "Streaming subscription",
    amount: 150,
    type: "withdraw",
    main_category: "Media and entertainment",
    sub_category: "Streaming services",
    date: "2025-09-06",
  },
  {
    description: "Dinner at restaurant",
    amount: 1100,
    type: "withdraw",
    main_category: "Cafe and restaurant",
    sub_category: "Restaurant",
    date: "2025-09-08",
  },
  {
    description: "Monthly public transport card",
    amount: 650,
    type: "withdraw",
    main_category: "Transportation and vehicles",
    sub_category: "Public transport",
    date: "2025-09-09",
  },
  {
    description: "Pharmacy purchase",
    amount: 520,
    type: "withdraw",
    main_category: "Health and wellbeing",
    sub_category: "Pharmacy",
    date: "2025-09-10",
  },
  {
    description: "Electricity bill",
    amount: 590,
    type: "withdraw",
    main_category: "Fixed living expenses",
    sub_category: "Electricity",
    date: "2025-09-12",
  },
  {
    description: "Online book order",
    amount: 850,
    type: "withdraw",
    main_category: "Miscellaneous",
    sub_category: "Training and education",
    date: "2025-09-14",
  },
  {
    description: "Pet food",
    amount: 780,
    type: "withdraw",
    main_category: "Hobby and leisure",
    sub_category: "Pets",
    date: "2025-09-15",
  },
  {
    description: "Coffee and snacks",
    amount: 420,
    type: "withdraw",
    main_category: "Cafe and restaurant",
    sub_category: "Cafe",
    date: "2025-09-17",
  },
  {
    description: "Freelance work payment",
    amount: 6000,
    type: "income",
    main_category: "Income",
    sub_category: "Other income",
    date: "2025-09-18",
  },
  {
    description: "Fuel for car",
    amount: 1550,
    type: "withdraw",
    main_category: "Transportation and vehicles",
    sub_category: "Fuel and charging",
    date: "2025-09-20",
  },
  {
    description: "Children's clothing",
    amount: 2000,
    type: "withdraw",
    main_category: "Children",
    sub_category: "Clothes",
    date: "2025-09-22",
  },
  {
    description: "Monthly gym fee",
    amount: 1200,
    type: "withdraw",
    main_category: "Health and wellbeing",
    sub_category: "Wellbeing",
    date: "2025-09-25",
  },
  {
    description: "Magazine subscription",
    amount: 350,
    type: "withdraw",
    main_category: "Media and entertainment",
    sub_category: "Magazines",
    date: "2025-09-27",
  },
  {
    description: "Interest from savings",
    amount: 340,
    type: "income",
    main_category: "Income",
    sub_category: "Dividends",
    date: "2025-09-28",
  },
] as const satisfies readonly DemoTransaction[];
