import { DemoTransaction } from "../types";

export const demo2025Q4 = [
  // 🌰 October
  {
    description: "Salary October",
    amount: 25000,
    type: "income",
    main_category: "Income",
    sub_category: "Wages",
    date: "2025-10-01",
  },
  {
    description: "Rent October",
    amount: 11000,
    type: "withdraw",
    main_category: "Fixed living expenses",
    sub_category: "Mortgage",
    date: "2025-10-03",
  },
  {
    description: "Groceries",
    amount: 2400,
    type: "withdraw",
    main_category: "Groceries",
    sub_category: "Supermarket",
    date: "2025-10-05",
  },
  {
    description: "Electricity bill",
    amount: 590,
    type: "withdraw",
    main_category: "Fixed living expenses",
    sub_category: "Electricity",
    date: "2025-10-07",
  },
  {
    description: "Taxi ride",
    amount: 400,
    type: "withdraw",
    main_category: "Transportation and vehicles",
    sub_category: "Taxi",
    date: "2025-10-10",
  },
  {
    description: "Cinema tickets",
    amount: 450,
    type: "withdraw",
    main_category: "Media and entertainment",
    sub_category: "Movie Theater",
    date: "2025-10-12",
  },
  {
    description: "Coffee and snacks",
    amount: 380,
    type: "withdraw",
    main_category: "Cafe and restaurant",
    sub_category: "Cafe",
    date: "2025-10-14",
  },
  {
    description: "Children's clothing",
    amount: 1000,
    type: "withdraw",
    main_category: "Children",
    sub_category: "Clothes",
    date: "2025-10-16",
  },
  {
    description: "Car maintenance",
    amount: 2200,
    type: "withdraw",
    main_category: "Transportation and vehicles",
    sub_category: "Car maintenance",
    date: "2025-10-18",
  },
  {
    description: "Pet supplies",
    amount: 850,
    type: "withdraw",
    main_category: "Hobby and leisure",
    sub_category: "Pets",
    date: "2025-10-20",
  },
  {
    description: "Home repair tools",
    amount: 950,
    type: "withdraw",
    main_category: "Home and garden",
    sub_category: "Tools",
    date: "2025-10-22",
  },
  {
    description: "Fuel",
    amount: 1500,
    type: "withdraw",
    main_category: "Transportation and vehicles",
    sub_category: "Fuel and charging",
    date: "2025-10-25",
  },
  {
    description: "Beauty salon visit",
    amount: 1200,
    type: "withdraw",
    main_category: "Health and wellbeing",
    sub_category: "Beauty",
    date: "2025-10-28",
  },
  {
    description: "Interest from savings",
    amount: 350,
    type: "income",
    main_category: "Income",
    sub_category: "Dividends",
    date: "2025-10-30",
  },
  // 🍂 November
  {
    description: "Salary November",
    amount: 25000,
    type: "income",
    main_category: "Income",
    sub_category: "Wages",
    date: "2025-11-01",
  },
  {
    description: "Rent November",
    amount: 11000,
    type: "withdraw",
    main_category: "Fixed living expenses",
    sub_category: "Mortgage",
    date: "2025-11-03",
  },
  {
    description: "Groceries",
    amount: 2500,
    type: "withdraw",
    main_category: "Groceries",
    sub_category: "Supermarket",
    date: "2025-11-05",
  },
  {
    description: "Electricity bill",
    amount: 600,
    type: "withdraw",
    main_category: "Fixed living expenses",
    sub_category: "Electricity",
    date: "2025-11-07",
  },
  {
    description: "Cinema tickets",
    amount: 500,
    type: "withdraw",
    main_category: "Media and entertainment",
    sub_category: "Movie Theater",
    date: "2025-11-09",
  },
  {
    description: "Taxi ride",
    amount: 450,
    type: "withdraw",
    main_category: "Transportation and vehicles",
    sub_category: "Taxi",
    date: "2025-11-11",
  },
  {
    description: "Gift for friend's birthday",
    amount: 1500,
    type: "withdraw",
    main_category: "Gifts and donations",
    sub_category: "Birthday gift",
    date: "2025-11-13",
  },
  {
    description: "Fuel",
    amount: 1700,
    type: "withdraw",
    main_category: "Transportation and vehicles",
    sub_category: "Fuel and charging",
    date: "2025-11-15",
  },
  {
    description: "Gym membership",
    amount: 1200,
    type: "withdraw",
    main_category: "Health and wellbeing",
    sub_category: "Wellbeing",
    date: "2025-11-17",
  },
  {
    description: "Monthly public transport card",
    amount: 650,
    type: "withdraw",
    main_category: "Transportation and vehicles",
    sub_category: "Public transport",
    date: "2025-11-19",
  },
  {
    description: "Online shopping (Clothes)",
    amount: 2500,
    type: "withdraw",
    main_category: "Clothing and gear",
    sub_category: "Clothing",
    date: "2025-11-21",
  },
  {
    description: "Lunch at restaurant",
    amount: 700,
    type: "withdraw",
    main_category: "Cafe and restaurant",
    sub_category: "Restaurant",
    date: "2025-11-23",
  },
  {
    description: "Family trip (Accommodation)",
    amount: 7500,
    type: "withdraw",
    main_category: "Travel",
    sub_category: "Accommodation",
    date: "2025-11-25",
  },
  {
    description: "Interest from savings",
    amount: 380,
    type: "income",
    main_category: "Income",
    sub_category: "Dividends",
    date: "2025-11-28",
  },
  {
    description: "Charity donation",
    amount: 800,
    type: "withdraw",
    main_category: "Miscellaneous",
    sub_category: "Charity",
    date: "2025-11-29",
  },
  // 🎄 December
  {
    description: "Salary December",
    amount: 25000,
    type: "income",
    main_category: "Income",
    sub_category: "Wages",
    date: "2025-12-01",
  },
  {
    description: "Rent December",
    amount: 11000,
    type: "withdraw",
    main_category: "Fixed living expenses",
    sub_category: "Mortgage",
    date: "2025-12-03",
  },
  {
    description: "Groceries",
    amount: 2500,
    type: "withdraw",
    main_category: "Groceries",
    sub_category: "Grocery store",
    date: "2025-12-05",
  },
  {
    description: "Christmas gifts",
    amount: 5000,
    type: "withdraw",
    main_category: "Gifts and donations",
    sub_category: "Christmas gifts",
    date: "2025-12-08",
  },
  {
    description: "Beauty salon visit",
    amount: 1200,
    type: "withdraw",
    main_category: "Health and wellbeing",
    sub_category: "Beauty",
    date: "2025-12-10",
  },
  {
    description: "Taxi ride",
    amount: 350,
    type: "withdraw",
    main_category: "Transportation and vehicles",
    sub_category: "Taxi",
    date: "2025-12-12",
  },
  {
    description: "Dinner at restaurant",
    amount: 1000,
    type: "withdraw",
    main_category: "Cafe and restaurant",
    sub_category: "Restaurant",
    date: "2025-12-15",
  },
  {
    description: "Fuel",
    amount: 1500,
    type: "withdraw",
    main_category: "Transportation and vehicles",
    sub_category: "Fuel and charging",
    date: "2025-12-17",
  },
  {
    description: "Streaming subscription",
    amount: 150,
    type: "withdraw",
    main_category: "Media and entertainment",
    sub_category: "Streaming services",
    date: "2025-12-20",
  },
  {
    description: "Electricity bill",
    amount: 600,
    type: "withdraw",
    main_category: "Fixed living expenses",
    sub_category: "Electricity",
    date: "2025-12-22",
  },
  {
    description: "Gym membership",
    amount: 1200,
    type: "withdraw",
    main_category: "Health and wellbeing",
    sub_category: "Wellbeing",
    date: "2025-12-24",
  },
  {
    description: "New Year's Eve party",
    amount: 2000,
    type: "withdraw",
    main_category: "Hobby and leisure",
    sub_category: "Events",
    date: "2025-12-28",
  },
  {
    description: "Interest from savings",
    amount: 380,
    type: "income",
    main_category: "Income",
    sub_category: "Dividends",
    date: "2025-12-30",
  },
] as const satisfies readonly DemoTransaction[];
